apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.Ingress }}
  namespace: {{ .Values.namespace }}
  annotations: 
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: common-alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-central-1:313422618945:certificate/bda8be21-5498-4b59-bd60-af381f8ad3e7
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.serviceName }}
            port:
              number: {{ .Values.servicePort }}