apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ns-deployment
  namespace: nginx-ns
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.16.1
        envFrom:
          - configMapRef:
              name: nginx-ns-host
          - secretRef:
              name: db-secret
        ports:
        - containerPort: 80