FROM node:18

# Create app directory
WORKDIR /usr/appstellar-stellar-web

# Install NEXT.js dependencies
COPY package.json /usr/appstellar-stellar-web/

# Build NEXT.js project
RUN npm install

COPY . /usr/appstellar-stellar-web/

# Build NEXT.js project
RUN npm run build

# Copy NEXT.js build artifacht to working directory
COPY . /usr/appstellar-stellar-web/

# Expose port 3000
EXPOSE 3000

# Run container with this command
CMD [ "npm", "run", "start" ]
